---
abstract: 'A standalone authoring tool for Module::Build::Tiny'
author:
  - 'Leon Timmermans <leont@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build::Tiny: '0.039'
dynamic_config: 0
generated_by: 'App::ModuleBuildTiny version 0.029, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-ModuleBuildTiny
provides:
  App::ModuleBuildTiny:
    file: lib/App/ModuleBuildTiny.pm
    version: '0.029'
  App::ModuleBuildTiny::Dist:
    file: lib/App/ModuleBuildTiny/Dist.pm
    version: '0.029'
requires:
  Archive::Tar: '0'
  CPAN::Meta: '0'
  CPAN::Meta::Merge: '0'
  CPAN::Meta::Prereqs::Filter: '0'
  CPAN::Upload::Tiny: '0.009'
  Data::Section::Simple: '0'
  Encode: '0'
  Exporter: '5.57'
  ExtUtils::Manifest: '0'
  File::Path: '0'
  File::Slurper: '0'
  File::Temp: '0'
  Getopt::Long: '2.36'
  JSON::PP: '0'
  Module::CPANfile: '0'
  Module::Metadata: '1.000037'
  Module::Runtime: '0'
  Parse::CPAN::Meta: '0'
  Pod::Simple::Text: '3.23'
  Software::LicenseUtils: '0.103014'
  Text::Template: '0'
  perl: '5.010'
resources:
  IRC: irc://irc.perl.org/#toolchain
  bugtracker: https://github.com/Leont/app-modulebuildtiny/issues
  repository: https://github.com/Leont/app-modulebuildtiny.git
version: '0.029'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
